apiVersion: v1
kind: PersistentVolume
metadata:
  name: dmsfiles
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-nfs-storage
  nfs:
    path: /srv/nfs
    server: 10.10.10.10
